#!/bin/sh
ssh ubuntu@3.18.212.171 <<EOF
    cd ~/ADYS2_ProyectoClase
    git pull origin master
    cd ./ParqueoWeb
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v14.9.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
